### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by damwhit** [sasloan/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [ ] I named my directories correctly. 
- [ ] I named my files correctly.
- [ ] I structured my files and directories correctly. 
- [ ] I made one initial commit.
- [ ] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [ ] I broke down larger processes into smaller layers.
- [ ] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
- [ ] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [ ] I structured and named my directories and files correctly.
- [ ] The four attributes I chose for **Class #1** represent properties or characteristics.
- [ ] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [ ] The four methods I chose for **Class #1** represent behaviors or actions.
- [ ] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [ ] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [ ] The object I chose for **Class 1** is an instance of this class. 
- [ ] I listed the values for each attribute of this object. 
- [ ] I listed the results of each method for this object. 
- [ ] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [ ] The four attributes I chose for **Class #2** represent states or characteristics.
- [ ] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [ ] The four methods I chose for **Class #2** represent behaviors or actions.
- [ ] I described what the methods do in **Class 2**, including which attributes they use or modify.
- [ ] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [ ] The object I chose for **Class 2** is an instance of this class. 
- [ ] I listed the values for each attribute of this object. 
- [ ] I listed the results of each method for this object. 
- [ ] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 

### Assessment Results
- [ ] Technical Ready
- [ ] Pending
- [ ] Not Technical Ready

**Comment by damwhit** [comment]
Hey Sebastian,

After reviewing your assessment, we'd like you to have another go around in mod 0. Here is some feedback for things to be thinking about:

* The top down design needs to be broken out using the numerical/decimal notation we laid out in session 5. It should also be stacked vertically and indented like we practiced in that class.
* There seems to be some confusion on classes vs. instances
  * Both algebra and english would be better served as instances of a "ClassSubject" class
* The classes in the class files should have laid out things in a similar way to what you did in class_2_example_object.txt
* In the example_object files we would have expected to see instances of a class, along with values filled in for both the attributes and methods
  * methods should utilize only attributes that you've defined.

Please don't hesitate to reach out with any questions.
